# Generated by Django 2.1.5 on 2019-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapp', '0002_auto_20190120_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleimage',
            name='image',
            field=models.ImageField(upload_to='character_images'),
        ),
    ]
